// Generated by `pnpm api:snapshot` from dist/index.d.ts. Do not edit.
//
// This is the published @scheme-tokens/material3 type surface.
import { TokenLayer, TokenVisibility } from "scheme-tokens";

declare const material3RoleDefinitions: readonly [{
  readonly engineMethod: "background";
  readonly tokenKey: "md.sys.color.background";
}, {
  readonly engineMethod: "onBackground";
  readonly tokenKey: "md.sys.color.on-background";
}, {
  readonly engineMethod: "surface";
  readonly tokenKey: "md.sys.color.surface";
}, {
  readonly engineMethod: "surfaceDim";
  readonly tokenKey: "md.sys.color.surface-dim";
}, {
  readonly engineMethod: "surfaceBright";
  readonly tokenKey: "md.sys.color.surface-bright";
}, {
  readonly engineMethod: "surfaceContainerLowest";
  readonly tokenKey: "md.sys.color.surface-container-lowest";
}, {
  readonly engineMethod: "surfaceContainerLow";
  readonly tokenKey: "md.sys.color.surface-container-low";
}, {
  readonly engineMethod: "surfaceContainer";
  readonly tokenKey: "md.sys.color.surface-container";
}, {
  readonly engineMethod: "surfaceContainerHigh";
  readonly tokenKey: "md.sys.color.surface-container-high";
}, {
  readonly engineMethod: "surfaceContainerHighest";
  readonly tokenKey: "md.sys.color.surface-container-highest";
}, {
  readonly engineMethod: "onSurface";
  readonly tokenKey: "md.sys.color.on-surface";
}, {
  readonly engineMethod: "surfaceVariant";
  readonly tokenKey: "md.sys.color.surface-variant";
}, {
  readonly engineMethod: "onSurfaceVariant";
  readonly tokenKey: "md.sys.color.on-surface-variant";
}, {
  readonly engineMethod: "inverseSurface";
  readonly tokenKey: "md.sys.color.inverse-surface";
}, {
  readonly engineMethod: "inverseOnSurface";
  readonly tokenKey: "md.sys.color.inverse-on-surface";
}, {
  readonly engineMethod: "outline";
  readonly tokenKey: "md.sys.color.outline";
}, {
  readonly engineMethod: "outlineVariant";
  readonly tokenKey: "md.sys.color.outline-variant";
}, {
  readonly engineMethod: "shadow";
  readonly tokenKey: "md.sys.color.shadow";
}, {
  readonly engineMethod: "scrim";
  readonly tokenKey: "md.sys.color.scrim";
}, {
  readonly engineMethod: "primary";
  readonly tokenKey: "md.sys.color.primary";
}, {
  readonly engineMethod: "onPrimary";
  readonly tokenKey: "md.sys.color.on-primary";
}, {
  readonly engineMethod: "primaryContainer";
  readonly tokenKey: "md.sys.color.primary-container";
}, {
  readonly engineMethod: "onPrimaryContainer";
  readonly tokenKey: "md.sys.color.on-primary-container";
}, {
  readonly engineMethod: "inversePrimary";
  readonly tokenKey: "md.sys.color.inverse-primary";
}, {
  readonly engineMethod: "secondary";
  readonly tokenKey: "md.sys.color.secondary";
}, {
  readonly engineMethod: "onSecondary";
  readonly tokenKey: "md.sys.color.on-secondary";
}, {
  readonly engineMethod: "secondaryContainer";
  readonly tokenKey: "md.sys.color.secondary-container";
}, {
  readonly engineMethod: "onSecondaryContainer";
  readonly tokenKey: "md.sys.color.on-secondary-container";
}, {
  readonly engineMethod: "tertiary";
  readonly tokenKey: "md.sys.color.tertiary";
}, {
  readonly engineMethod: "onTertiary";
  readonly tokenKey: "md.sys.color.on-tertiary";
}, {
  readonly engineMethod: "tertiaryContainer";
  readonly tokenKey: "md.sys.color.tertiary-container";
}, {
  readonly engineMethod: "onTertiaryContainer";
  readonly tokenKey: "md.sys.color.on-tertiary-container";
}, {
  readonly engineMethod: "error";
  readonly tokenKey: "md.sys.color.error";
}, {
  readonly engineMethod: "onError";
  readonly tokenKey: "md.sys.color.on-error";
}, {
  readonly engineMethod: "errorContainer";
  readonly tokenKey: "md.sys.color.error-container";
}, {
  readonly engineMethod: "onErrorContainer";
  readonly tokenKey: "md.sys.color.on-error-container";
}, {
  readonly engineMethod: "primaryFixed";
  readonly tokenKey: "md.sys.color.primary-fixed";
}, {
  readonly engineMethod: "primaryFixedDim";
  readonly tokenKey: "md.sys.color.primary-fixed-dim";
}, {
  readonly engineMethod: "onPrimaryFixed";
  readonly tokenKey: "md.sys.color.on-primary-fixed";
}, {
  readonly engineMethod: "onPrimaryFixedVariant";
  readonly tokenKey: "md.sys.color.on-primary-fixed-variant";
}, {
  readonly engineMethod: "secondaryFixed";
  readonly tokenKey: "md.sys.color.secondary-fixed";
}, {
  readonly engineMethod: "secondaryFixedDim";
  readonly tokenKey: "md.sys.color.secondary-fixed-dim";
}, {
  readonly engineMethod: "onSecondaryFixed";
  readonly tokenKey: "md.sys.color.on-secondary-fixed";
}, {
  readonly engineMethod: "onSecondaryFixedVariant";
  readonly tokenKey: "md.sys.color.on-secondary-fixed-variant";
}, {
  readonly engineMethod: "tertiaryFixed";
  readonly tokenKey: "md.sys.color.tertiary-fixed";
}, {
  readonly engineMethod: "tertiaryFixedDim";
  readonly tokenKey: "md.sys.color.tertiary-fixed-dim";
}, {
  readonly engineMethod: "onTertiaryFixed";
  readonly tokenKey: "md.sys.color.on-tertiary-fixed";
}, {
  readonly engineMethod: "onTertiaryFixedVariant";
  readonly tokenKey: "md.sys.color.on-tertiary-fixed-variant";
}];
type Material3Appearance = "light" | "dark";
type Material3SpecVersion = "2021" | "2025";
type Material3Variant = "monochrome" | "neutral" | "tonal-spot" | "vibrant" | "expressive" | "fidelity" | "content" | "rainbow" | "fruit-salad";
type Material3TokenKey = (typeof material3RoleDefinitions)[number]["tokenKey"];
interface Material3ModeOverrides {
  readonly sourceColor?: string;
  readonly variant?: Material3Variant;
  readonly contrastLevel?: number;
}
type Material3ModeConfig<Key extends string> = Key extends "light" | "dark" ? Material3ModeOverrides & {
  readonly appearance?: never;
} : Material3ModeOverrides & {
  readonly appearance: Material3Appearance;
};
type Material3BuiltInMode = "light" | "dark";
type Material3AdditiveModeMap<Extra extends string> = { readonly [Key in Material3BuiltInMode | Extra]?: Material3ModeConfig<Key> };
type Material3ExactModeMap<Mode extends string> = { readonly [Key in Mode]: Material3ModeConfig<Key> };
interface Material3BaseOptions {
  readonly specVersion?: Material3SpecVersion;
  readonly variant?: Material3Variant;
  readonly contrastLevel?: number;
  readonly visibility?: TokenVisibility;
}
type Material3AdditiveModeOptions<Extra extends string> = Material3BaseOptions & {
  readonly modes?: Material3AdditiveModeMap<Extra>;
  readonly exactModes?: never;
  readonly defaultMode?: NoInfer<Material3BuiltInMode | Extra>;
};
type Material3ExactModeOptions<Mode extends string> = Material3BaseOptions & {
  readonly modes?: never;
  readonly exactModes: Material3ExactModeMap<Mode>;
  readonly defaultMode: NoInfer<Mode>;
};
interface Material3GraphFragment<Mode extends string> {
  readonly modes: readonly [Mode, ...Mode[]];
  readonly defaultMode: Mode;
  readonly layers: readonly [TokenLayer<Material3TokenKey>];
}
declare function material3<const Mode extends string>(sourceColor: string, options: Material3ExactModeOptions<Mode>): Material3GraphFragment<Mode>;
declare function material3<const Extra extends string = never>(sourceColor: string, options?: Material3AdditiveModeOptions<Extra>): Material3GraphFragment<"light" | "dark" | Extra>;
export { type Material3Appearance, type Material3GraphFragment, type Material3SpecVersion, type Material3TokenKey, type Material3Variant, material3 };
