import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
export const repoRoot = dirname(dirname(packageRoot));
export const snapshotPath = join(packageRoot, "api", "material3.api.d.ts");
export const snapshotLabel = "packages/material3/api/material3.api.d.ts";

const header = [
  "// Generated by `pnpm api:snapshot` from dist/index.d.ts. Do not edit.",
  "//",
  "// This is the published @scheme-tokens/material3 type surface.",
  "",
].join("\n");

export function buildSnapshot(declaration: string): string {
  const body = declaration
    .replaceAll("\r\n", "\n")
    .split("\n")
    .filter(
      (line) =>
        !line.startsWith("//#region") &&
        !line.startsWith("//#endregion") &&
        !line.startsWith("//# sourceMappingURL="),
    )
    .join("\n")
    .replace(/\n{3,}/gu, "\n\n")
    .trim();
  return `${header}${body}\n`;
}

export function buildSnapshotFromDist(): string {
  return buildSnapshot(readFileSync(join(packageRoot, "dist", "index.d.ts"), "utf8"));
}
