export const material3RoleDefinitions = [
  { engineMethod: "background", tokenKey: "md.sys.color.background" },
  { engineMethod: "onBackground", tokenKey: "md.sys.color.on-background" },
  { engineMethod: "surface", tokenKey: "md.sys.color.surface" },
  { engineMethod: "surfaceDim", tokenKey: "md.sys.color.surface-dim" },
  { engineMethod: "surfaceBright", tokenKey: "md.sys.color.surface-bright" },
  {
    engineMethod: "surfaceContainerLowest",
    tokenKey: "md.sys.color.surface-container-lowest",
  },
  { engineMethod: "surfaceContainerLow", tokenKey: "md.sys.color.surface-container-low" },
  { engineMethod: "surfaceContainer", tokenKey: "md.sys.color.surface-container" },
  { engineMethod: "surfaceContainerHigh", tokenKey: "md.sys.color.surface-container-high" },
  {
    engineMethod: "surfaceContainerHighest",
    tokenKey: "md.sys.color.surface-container-highest",
  },
  { engineMethod: "onSurface", tokenKey: "md.sys.color.on-surface" },
  { engineMethod: "surfaceVariant", tokenKey: "md.sys.color.surface-variant" },
  { engineMethod: "onSurfaceVariant", tokenKey: "md.sys.color.on-surface-variant" },
  { engineMethod: "inverseSurface", tokenKey: "md.sys.color.inverse-surface" },
  { engineMethod: "inverseOnSurface", tokenKey: "md.sys.color.inverse-on-surface" },
  { engineMethod: "outline", tokenKey: "md.sys.color.outline" },
  { engineMethod: "outlineVariant", tokenKey: "md.sys.color.outline-variant" },
  { engineMethod: "shadow", tokenKey: "md.sys.color.shadow" },
  { engineMethod: "scrim", tokenKey: "md.sys.color.scrim" },
  { engineMethod: "primary", tokenKey: "md.sys.color.primary" },
  { engineMethod: "onPrimary", tokenKey: "md.sys.color.on-primary" },
  { engineMethod: "primaryContainer", tokenKey: "md.sys.color.primary-container" },
  { engineMethod: "onPrimaryContainer", tokenKey: "md.sys.color.on-primary-container" },
  { engineMethod: "inversePrimary", tokenKey: "md.sys.color.inverse-primary" },
  { engineMethod: "secondary", tokenKey: "md.sys.color.secondary" },
  { engineMethod: "onSecondary", tokenKey: "md.sys.color.on-secondary" },
  { engineMethod: "secondaryContainer", tokenKey: "md.sys.color.secondary-container" },
  {
    engineMethod: "onSecondaryContainer",
    tokenKey: "md.sys.color.on-secondary-container",
  },
  { engineMethod: "tertiary", tokenKey: "md.sys.color.tertiary" },
  { engineMethod: "onTertiary", tokenKey: "md.sys.color.on-tertiary" },
  { engineMethod: "tertiaryContainer", tokenKey: "md.sys.color.tertiary-container" },
  { engineMethod: "onTertiaryContainer", tokenKey: "md.sys.color.on-tertiary-container" },
  { engineMethod: "error", tokenKey: "md.sys.color.error" },
  { engineMethod: "onError", tokenKey: "md.sys.color.on-error" },
  { engineMethod: "errorContainer", tokenKey: "md.sys.color.error-container" },
  { engineMethod: "onErrorContainer", tokenKey: "md.sys.color.on-error-container" },
  { engineMethod: "primaryFixed", tokenKey: "md.sys.color.primary-fixed" },
  { engineMethod: "primaryFixedDim", tokenKey: "md.sys.color.primary-fixed-dim" },
  { engineMethod: "onPrimaryFixed", tokenKey: "md.sys.color.on-primary-fixed" },
  {
    engineMethod: "onPrimaryFixedVariant",
    tokenKey: "md.sys.color.on-primary-fixed-variant",
  },
  { engineMethod: "secondaryFixed", tokenKey: "md.sys.color.secondary-fixed" },
  { engineMethod: "secondaryFixedDim", tokenKey: "md.sys.color.secondary-fixed-dim" },
  { engineMethod: "onSecondaryFixed", tokenKey: "md.sys.color.on-secondary-fixed" },
  {
    engineMethod: "onSecondaryFixedVariant",
    tokenKey: "md.sys.color.on-secondary-fixed-variant",
  },
  { engineMethod: "tertiaryFixed", tokenKey: "md.sys.color.tertiary-fixed" },
  { engineMethod: "tertiaryFixedDim", tokenKey: "md.sys.color.tertiary-fixed-dim" },
  { engineMethod: "onTertiaryFixed", tokenKey: "md.sys.color.on-tertiary-fixed" },
  {
    engineMethod: "onTertiaryFixedVariant",
    tokenKey: "md.sys.color.on-tertiary-fixed-variant",
  },
] as const;

export const excludedEngineRoles = {
  primaryPaletteKeyColor: "palette-key",
  secondaryPaletteKeyColor: "palette-key",
  tertiaryPaletteKeyColor: "palette-key",
  neutralPaletteKeyColor: "palette-key",
  neutralVariantPaletteKeyColor: "palette-key",
  errorPaletteKeyColor: "palette-key",
  primaryDim: "incoherent-pre-2025-role",
  secondaryDim: "incoherent-pre-2025-role",
  tertiaryDim: "incoherent-pre-2025-role",
  errorDim: "incoherent-pre-2025-role",
  surfaceTint: "deprecated-md-sys-token",
} as const;

export const material3HelperMethods = ["highestSurface"] as const;

export type Material3EngineMethod = (typeof material3RoleDefinitions)[number]["engineMethod"];
