import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));
export const snapshotPath = join(repoRoot, "api", "scheme-tokens.api.d.ts");
export const snapshotLabel = "api/scheme-tokens.api.d.ts";

const header = [
  "// Generated by `pnpm api:snapshot` from dist/index.d.ts. Do not edit.",
  "//",
  "// This is the published type surface. A diff here is a consumer-visible API",
  "// change and needs a changeset; CI enforces that pairing.",
  "",
].join("\n");

/**
 * Bundler region markers and the source-map comment describe how the
 * declaration was emitted, not what it exports, so they are dropped: they would
 * otherwise churn the snapshot on unrelated build changes.
 */
export function buildSnapshot(declaration: string): string {
  const body = declaration
    .replaceAll("\r\n", "\n")
    .split("\n")
    .filter(
      (line) =>
        !line.startsWith("//#region") &&
        !line.startsWith("//#endregion") &&
        !line.startsWith("//# sourceMappingURL="),
    )
    .join("\n")
    .replace(/\n{3,}/gu, "\n\n")
    .trim();

  return `${header}${body}\n`;
}

export function buildSnapshotFromDist(): string {
  return buildSnapshot(readFileSync(join(repoRoot, "dist", "index.d.ts"), "utf8"));
}
