// Generated by `pnpm api:snapshot` from dist/index.d.ts. Do not edit.
//
// This is the published type surface. A diff here is a consumer-visible API
// change and needs a changeset; CI enforces that pairing.
interface Issue<Code extends string = string> {
  readonly code: Code;
  readonly message: string;
  readonly path?: string;
}
type NonEmptyIssues<I> = readonly [I, ...I[]];
type FailureResult<Problem = Issue> = {
  readonly ok: false;
  readonly issues: NonEmptyIssues<Problem>;
};
type Result<Value, Problem = Issue> = {
  readonly ok: true;
  readonly value: Value;
} | FailureResult<Problem>;
type JsonPrimitive = null | boolean | number | string;
type JsonValue = JsonPrimitive | readonly JsonValue[] | {
  readonly [key: string]: JsonValue;
};
declare const tokenGraphKind = "scheme-tokens/token-graph";
declare const tokenLayerKind = "scheme-tokens/token-layer";
declare const compiledSchemeKind = "scheme-tokens/compiled-scheme";
declare const tokenGraphSchemaUrl = "https://scheme-tokens.dev/schemas/token-graph.v1.schema.json";
declare const tokenLayerSchemaUrl = "https://scheme-tokens.dev/schemas/token-layer.v1.schema.json";
declare const compiledSchemeSchemaUrl = "https://scheme-tokens.dev/schemas/compiled-scheme.v1.schema.json";
type TokenVisibility = "public" | "internal";
interface TokenReference<Key extends string = string> {
  readonly ref: Key;
}
type TokenExpression<Key extends string = string> = string | TokenReference<Key>;
type TokenModeValues<Mode extends string, Key extends string> = Readonly<Record<Mode, TokenExpression<Key>>>;
interface TokenDefinitionMetadata {
  readonly visibility?: TokenVisibility;
  readonly description?: string;
  readonly deprecated?: boolean | string;
  readonly extensions?: Readonly<Record<string, JsonValue>>;
}
type TokenDefinition<Key extends string = string, Mode extends string = string> = TokenDefinitionMetadata & {
  readonly value: TokenExpression<Key> | TokenModeValues<Mode, Key>;
};
interface TokenLayer<Key extends string = string, Mode extends string = string> {
  readonly $schema?: typeof tokenLayerSchemaUrl;
  readonly kind: typeof tokenLayerKind;
  readonly formatVersion: 1;
  readonly id: string;
  readonly defaultVisibility: TokenVisibility;
  readonly tokens: Readonly<Record<Key, TokenDefinition<string, Mode>>>;
}
interface TokenGraph<Key extends string = string, Mode extends string = string, Layers extends readonly TokenLayer<string, string>[] = readonly TokenLayer<string, string>[]> {
  readonly $schema?: typeof tokenGraphSchemaUrl;
  readonly kind: typeof tokenGraphKind;
  readonly formatVersion: 1;
  readonly modes: readonly [Mode, ...Mode[]];
  readonly defaultMode: Mode;
  readonly defaultVisibility: TokenVisibility;
  readonly tokens: Readonly<Record<Key, TokenDefinition<string, Mode>>>;
  readonly layers?: Layers;
}
type TokenMetadataAuthoring = TokenDefinitionMetadata;
type ExpandedSingleTokenAuthoring<Key extends string> = TokenMetadataAuthoring & {
  readonly value: TokenExpression<Key>;
};
type ExpandedMultiTokenAuthoring<Mode extends string, Key extends string> = TokenMetadataAuthoring & {
  readonly value: TokenExpression<Key> | TokenModeValues<Mode, Key>;
};
type SingleTokenAuthoring<Key extends string> = TokenExpression<Key> | ExpandedSingleTokenAuthoring<Key>;
type MultiTokenAuthoring<Mode extends string, Key extends string> = TokenExpression<Key> | TokenModeValues<Mode, Key> | ExpandedMultiTokenAuthoring<Mode, Key>;
type ModeTuple = readonly [string, ...string[]];
type LayerTuple = readonly TokenLayer<string, string>[];
type ReservedMode = "ref" | "value" | "valueByMode" | "visibility" | "description" | "deprecated" | "extensions";
type ValidModes<Modes extends ModeTuple> = Extract<Modes[number], ReservedMode> extends never ? Modes : never;
type LayerMemberKey<Layer> = Layer extends TokenLayer<infer Key, string> ? Key : never;
type LayerKeyOf<Layers extends LayerTuple> = Layers extends readonly [] ? never : LayerMemberKey<Layers[number]>;
type DefinedGraph<DirectKey extends string, Mode extends string, Layers extends LayerTuple> = TokenGraph<DirectKey, Mode, Layers>;
interface SharedGraphOptions<Layers extends LayerTuple> {
  readonly $schema?: typeof tokenGraphSchemaUrl;
  readonly defaultVisibility?: TokenVisibility;
  readonly layers?: Layers;
}
type SingleGraphOptions<Layers extends LayerTuple> = SharedGraphOptions<Layers> & {
  readonly modes?: never;
  readonly defaultMode?: never;
};
type MultiGraphOptions<Modes extends ModeTuple, Layers extends LayerTuple> = SharedGraphOptions<Layers> & {
  readonly modes: ValidModes<Modes>;
  readonly defaultMode: NoInfer<Modes[number]>;
};
type SingleGraphAuthoring<DirectKey extends string, Layers extends LayerTuple> = SingleGraphOptions<Layers> & {
  readonly tokens: Readonly<Record<DirectKey, SingleTokenAuthoring<NoInfer<DirectKey | LayerKeyOf<Layers>>>>>;
};
type MultiGraphAuthoring<Modes extends ModeTuple, DirectKey extends string, Layers extends LayerTuple> = MultiGraphOptions<Modes, Layers> & {
  readonly tokens: Readonly<Record<DirectKey, MultiTokenAuthoring<NoInfer<Modes[number]>, NoInfer<DirectKey | LayerKeyOf<Layers>>>>>;
};
type TokenOrigin = {
  readonly kind: "graph";
} | {
  readonly kind: "layer";
  readonly id: string;
};
type DirectTokenKeyOf<T> = T extends {
  readonly tokens: Readonly<Record<infer Key, unknown>>;
} ? Extract<Key, string> : never;
type TokenKeyOf<T> = T extends TokenGraph<infer DirectKey, string, infer Layers> ? DirectKey | LayerKeyOf<Layers> : DirectTokenKeyOf<T>;
type ModeOf<T> = T extends {
  readonly modes: readonly [infer First, ...infer Rest];
} ? Extract<First | Rest[number], string> : never;
type TokenGraphIssue = Issue<"invalid-object" | "unknown-property" | "missing-property" | "invalid-artifact-kind" | "invalid-format-version" | "invalid-schema-uri" | "invalid-json-value" | "empty-modes" | "invalid-mode-key" | "duplicate-mode-key" | "default-mode-not-found" | "invalid-default-visibility" | "invalid-layer-id" | "duplicate-layer-id" | "invalid-token-key" | "invalid-visibility" | "invalid-token-definition" | "missing-token-value" | "invalid-token-value" | "missing-mode-value" | "unknown-mode-value" | "invalid-reference" | "unknown-reference" | "reference-cycle" | "invalid-description" | "invalid-deprecated" | "invalid-extensions"> & {
  readonly key?: string;
  readonly mode?: string;
  readonly layerId?: string;
  readonly firstPath?: string;
  readonly cycle?: readonly string[];
};
declare function tokenRef<const Key extends string>(key: Key): TokenReference<Key>;
declare function defineTokens<const Key extends string, const Layers extends LayerTuple = readonly []>(tokens: Readonly<Record<Key, SingleTokenAuthoring<NoInfer<Key | LayerKeyOf<Layers>>>>>, options?: SingleGraphOptions<Layers>): DefinedGraph<Key, "base", Layers>;
declare function defineTokens<const Modes extends ModeTuple, const Key extends string, const Layers extends LayerTuple = readonly []>(tokens: Readonly<Record<Key, MultiTokenAuthoring<NoInfer<Modes[number]>, NoInfer<Key | LayerKeyOf<Layers>>>>>, options: MultiGraphOptions<Modes, Layers>): DefinedGraph<Key, Modes[number], Layers>;
declare function defineTokenGraph<const DirectKey extends string, const Layers extends LayerTuple = readonly []>(input: SingleGraphAuthoring<DirectKey, Layers>): DefinedGraph<DirectKey, "base", Layers>;
declare function defineTokenGraph<const Modes extends ModeTuple, const DirectKey extends string, const Layers extends LayerTuple = readonly []>(input: MultiGraphAuthoring<Modes, DirectKey, Layers>): DefinedGraph<DirectKey, Modes[number], Layers>;
declare function defineTokenLayer<const Key extends string>(input: {
  readonly $schema?: typeof tokenLayerSchemaUrl;
  readonly id: string;
  readonly defaultVisibility?: TokenVisibility;
  readonly tokens: Readonly<Record<Key, MultiTokenAuthoring<string, string>>>;
}): TokenLayer<Key, string>;
declare function parseTokenGraph(input: unknown): Result<TokenGraph, TokenGraphIssue>;
declare function parseTokenLayer(input: unknown): Result<TokenLayer, TokenGraphIssue>;
type TokenSelection<Key extends string = string> = "public" | "all" | {
  readonly keys: readonly Key[];
};
interface CompileTokenGraphOptions<Key extends string = string> {
  readonly selection?: TokenSelection<Key>;
}
type CompileSelectionIssue = Issue<"invalid-compile-options" | "invalid-selection" | "empty-selection" | "invalid-selection-key" | "duplicate-selection-key" | "unknown-selection-key" | "no-selected-tokens"> & {
  readonly key?: string;
};
type CompileTokenGraphIssue = TokenGraphIssue | CompileSelectionIssue;
type CompiledToken<Mode extends string = string> = Readonly<Record<Mode, string>>;
type CompiledRecord<Key extends string, Value, Complete extends boolean> = Complete extends true ? Readonly<Record<Key, Value>> : Readonly<Partial<Record<Key, Value>>>;
interface CompiledTokenMetadata<Mode extends string = string> {
  readonly visibility: TokenVisibility;
  readonly origin: TokenOrigin;
  readonly dependenciesByMode: Readonly<Record<Mode, readonly string[]>>;
  readonly description?: string;
  readonly deprecated?: boolean | string;
  readonly extensions?: Readonly<Record<string, JsonValue>>;
}
interface CompiledScheme<Key extends string = string, Mode extends string = string, Complete extends boolean = true> {
  readonly $schema?: typeof compiledSchemeSchemaUrl;
  readonly kind: typeof compiledSchemeKind;
  readonly formatVersion: 1;
  readonly modes: readonly [Mode, ...Mode[]];
  readonly defaultMode: Mode;
  readonly tokens: CompiledRecord<Key, CompiledToken<Mode>, Complete>;
  readonly metadataByToken: CompiledRecord<Key, CompiledTokenMetadata<Mode>, Complete>;
}
type ParseCompiledSchemeIssue = Issue<"invalid-object" | "unknown-property" | "missing-property" | "invalid-artifact-kind" | "invalid-format-version" | "invalid-schema-uri" | "invalid-mode-key" | "duplicate-mode-key" | "default-mode-not-found" | "invalid-token-key" | "invalid-visibility" | "invalid-token-definition" | "invalid-token-value" | "missing-mode-value" | "unknown-mode-value" | "invalid-origin" | "invalid-dependencies" | "invalid-description" | "invalid-deprecated" | "invalid-extensions" | "invalid-json-value"> & {
  readonly key?: string;
  readonly mode?: string;
};
declare function parseCompiledScheme(input: unknown): Result<CompiledScheme<string, string, false>, ParseCompiledSchemeIssue>;
type SelectedKey<Input, Options> = Options extends {
  readonly selection: {
    readonly keys: readonly (infer Key)[];
  };
} ? Extract<Key, string> : TokenKeyOf<Input>;
type HasFiniteKeys<Key extends string> = string extends Key ? false : true;
type CompleteSelection<Input, Options> = Options extends {
  readonly selection: "all";
} ? HasFiniteKeys<TokenKeyOf<Input>> : Options extends {
  readonly selection: {
    readonly keys: infer Keys extends readonly string[];
  };
} ? number extends Keys["length"] ? false : true : false;
type CompiledGraphResult<Input, Options> = Result<CompiledScheme<SelectedKey<Input, Options>, ModeOf<Input>, CompleteSelection<Input, Options>>, CompileTokenGraphIssue>;
/**
 * Compile a token graph into deterministic token mode maps and metadata.
 */
declare function compileTokenGraph<const Input extends TokenGraph>(input: Input): CompiledGraphResult<Input, undefined>;
declare function compileTokenGraph<const Input extends TokenGraph, const Options extends CompileTokenGraphOptions<TokenKeyOf<Input>>>(input: Input, options: Options): CompiledGraphResult<Input, Options>;
type CssScope = {
  readonly strategy: "root";
} | {
  readonly strategy: "selector";
  readonly selector: string;
};
type CssModeSelectors<Mode extends string = string> = {
  readonly strategy: "data-attribute";
  readonly attribute: string;
} | {
  readonly strategy: "class";
  readonly classPrefix: string;
} | {
  readonly strategy: "selectors";
  readonly selectors: Readonly<Record<Mode, string>>;
};
interface CssVariableNameInput<Key extends string = string> {
  readonly tokenKey: Key;
  readonly segments: readonly [string, ...string[]];
  readonly defaultName: string;
  readonly prefix?: string;
}
interface ExportCssVarsOptions<Key extends string = string, Mode extends string = string> {
  readonly prefix?: string;
  readonly variableName?: (input: CssVariableNameInput<Key>) => string;
  readonly scope?: CssScope;
  readonly modeSelectors?: CssModeSelectors<Mode>;
  readonly format?: "pretty" | "compact";
}
interface CssVarDeclaration<Key extends string = string> {
  readonly tokenKey: Key;
  readonly property: string;
  readonly value: string;
}
interface CssVarBlock<Key extends string = string, Mode extends string = string> {
  readonly mode: Mode;
  readonly selector: string;
  readonly declarations: readonly CssVarDeclaration<Key>[];
}
type CssVariableMap<Key extends string, Complete extends boolean> = Complete extends true ? Readonly<Record<Key, string>> : Readonly<Partial<Record<Key, string>>>;
interface CssVarsExport<Key extends string = string, Mode extends string = string, Complete extends boolean = true> {
  readonly css: string;
  readonly blocks: readonly CssVarBlock<Key, Mode>[];
  readonly variableByToken: CssVariableMap<Key, Complete>;
}
type ExportCssVarsIssue = ParseCompiledSchemeIssue | (Issue<"invalid-css-options" | "invalid-css-prefix" | "invalid-css-variable" | "invalid-css-value" | "duplicate-css-variable" | "invalid-scope" | "invalid-selector" | "invalid-data-attribute" | "invalid-class-prefix" | "invalid-mode-selectors" | "missing-mode-selector" | "unknown-mode-selector" | "duplicate-mode-selector"> & {
  readonly key?: string;
  readonly firstKey?: string;
  readonly mode?: string;
  readonly property?: string;
  readonly selector?: string;
});
type AnyCompiledScheme$1 = CompiledScheme<string, string, boolean>;
type SchemeKey<Scheme extends AnyCompiledScheme$1> = Extract<keyof Scheme["tokens"], string>;
type SchemeMode<Scheme extends AnyCompiledScheme$1> = Extract<Scheme["modes"][number], string>;
type SchemeCompleteness<Scheme extends AnyCompiledScheme$1> = Scheme extends CompiledScheme<string, string, infer Complete> ? Complete : boolean;
type ExportCssVarsOptionsFor<Scheme extends AnyCompiledScheme$1> = ExportCssVarsOptions<SchemeKey<Scheme>, SchemeMode<Scheme>>;
type ExportedCssVars<Scheme extends AnyCompiledScheme$1> = Result<CssVarsExport<SchemeKey<Scheme>, SchemeMode<Scheme>, SchemeCompleteness<Scheme>>, ExportCssVarsIssue>;
/**
 * Export a compiled scheme as deterministic CSS custom properties.
 */
declare function exportCssVars<const Scheme extends AnyCompiledScheme$1>(scheme: Scheme, options?: ExportCssVarsOptionsFor<Scheme>): ExportedCssVars<Scheme>;
declare function serializeTokenGraph(graph: TokenGraph): string;
declare function serializeTokenLayer(layer: TokenLayer): string;
type AnyCompiledScheme = CompiledScheme<string, string, boolean>;
declare function serializeCompiledScheme(scheme: AnyCompiledScheme): string;
export { type CompileTokenGraphIssue, type CompileTokenGraphOptions, type CompiledScheme, type CompiledToken, type CompiledTokenMetadata, type CssModeSelectors, type CssScope, type CssVarBlock, type CssVarDeclaration, type CssVarsExport, type ExportCssVarsIssue, type ExportCssVarsOptions, type Issue, type JsonValue, type ParseCompiledSchemeIssue, type Result, type TokenDefinition, type TokenExpression, type TokenGraph, type TokenGraphIssue, type TokenLayer, type TokenOrigin, type TokenReference, type TokenSelection, type TokenVisibility, compileTokenGraph, defineTokenGraph, defineTokenLayer, defineTokens, exportCssVars, parseCompiledScheme, parseTokenGraph, parseTokenLayer, serializeCompiledScheme, serializeTokenGraph, serializeTokenLayer, tokenRef };
